id: P009232
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-19 19:29:11.757292
source_metadata:
  id: bdr:W24790
  title: གསུང་འབུམ། བློ་བཟང་ལུང་རྟོགས་བསྟན་པའི་རྒྱལ་མཚན
  author: ''
  volumes:
    17e1727628f74f0aaccae558e95bbc92:
      image_group_id: I00KG09988
      title: ''
      volume_number: 1
      total_pages: 782
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
